[project]
name = "openshift-pod-watcher"
version = "0.1.0"
description = "Tracks openshift pods' resource requests"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
  "requests",
  "kubernetes",
]
