apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: pod-watcher-binding
subjects:
  - kind: ServiceAccount
    name: pod-watcher-sa
roleRef:
  kind: ClusterRole
  name: pod-watcher-clusterrole
  apiGroup: rbac.authorization.k8s.io
